name: Conventional Commits

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  conventional-commits:
    uses: OmnisGenomics/.github/.github/workflows/maintenance.yml@main
    with:
      check_flake: false
      report_artifact_name: conventional-commits-${{ github.run_id }}-${{ github.run_attempt }}
      maintenance_command: |
        git fetch --no-tags --depth=2 origin "${GITHUB_REF_NAME}"
        if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
          rev_range=HEAD~1..HEAD
        else
          rev_range=HEAD
        fi
        nix run .#conventional-commits -- "$rev_range"
    secrets:
      MONARCHIC_GITHUB_PAT: ${{ secrets.MONARCHIC_GITHUB_PAT }}
