name: Publish CLI

on:
  push:
    tags:
      - "cli-v*"

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  publish:
    uses: OmnisGenomics/.github/.github/workflows/npm-publish.yml@main
    with:
      tag_pattern: '^cli-v[0-9]+[.][0-9]+[.][0-9]+$'
      tag_prefix: cli-v
      install_command: pnpm install --frozen-lockfile
      required_workflow: Nix CI
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      MONARCHIC_GITHUB_PAT: ${{ secrets.MONARCHIC_GITHUB_PAT }}
